id: I544D1915
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T11:11:24+00:00'
last_modified: '2022-06-08T11:59:43.987336+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23218
  title: གསུང་འབུམ། ཀུན་དགའ་ལྷུན་གྲུབ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    8C44:
      image_group_id: I1PD26329
      title: ''
      total_pages: 428
      order: 1
      base_file: 8C44.txt
    89BB:
      image_group_id: I1PD26330
      title: ''
      total_pages: 396
      order: 2
      base_file: 89BB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
