id: I544D1915
legacy_id: P009574
ocr_import_info:
  bdrc_scan_id: W23218
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T11:09:01'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T01:00:21.738506+00:00'
last_modified: 2022-09-02 09:00:42.514821
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W23218
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW23218
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། ཀུན་དགའ་ལྷུན་གྲུབ།
  author: བདེ་ཆེན་ཆོས་འཁོར་ཡོངས་འཛིན ༠༢་ཀུན་དགའ་ལྷུན་གྲུབ།
statistics:
  ocr_word_mean_confidence_index: 0.5994894265181105
  ocr_word_median_confidence_index: 0.6200000047683716
quality: null
bases:
  I1PD26329:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD26329
      total_pages: 428
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1PD26329.txt
    statistics:
      ocr_word_median_confidence_index: 0.49000000953674316
      ocr_word_mean_confidence_index: 0.5340382120853558
    legacy_id: v001
  I1PD26330:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD26330
      total_pages: 396
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1PD26330.txt
    statistics:
      ocr_word_median_confidence_index: 0.6800000071525574
      ocr_word_mean_confidence_index: 0.647571893311813
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
